version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:384
        environment:
            - WORLD_SEED=1234

    python3-agent:
        build:
            context: app
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: app
            dockerfile: Dockerfile
        volumes:
            - ./app:/app

    python3-fwd:
        build:
            context: app
            dockerfile: Dockerfile.fwd

    python3-fwd-dev:
        build:
            context: app
            dockerfile: Dockerfile.fwd.dev
        volumes:
            - ./app:/app

    typescript-agent:
        build:
            context: typescript
            dockerfile: Dockerfile

    typescript-agent-dev:
        build:
            context: typescript
            dockerfile: Dockerfile.dev
        volumes:
            - ./typescript:/app
