version: "3"
services:
    game-server:
        image: coderone.azurecr.io/game-server:384
        environment:
            - WORLD_SEED=1234

    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile

    python3-agent-dev:
        build:
            context: python3
            dockerfile: Dockerfile
        volumes:
            - ./python3:/app

    python3-hill_climber:
        build:
            context: python3/
            dockerfile: app/enemies/hill_climber/Dockerfile

    python3-scrim-one:
        build:
            context: python3/
            dockerfile: app/enemies/scrim-one/Dockerfile
