version: "3"
services:
    game-server:
        extends:
            file: base-compose.yml
            service: game-server
        ports:
            - 3000:3000
        environment:
            - ADMIN_ROLE_ENABLED=0
            - AGENT_ID_MAPPING=agentA,agentB
            - INITIAL_AMMUNITION=3
            - INITIAL_HP=3
            - PRNG_SEED=1234
            - SHUTDOWN_ON_GAME_END_ENABLED=1
            - TELEMETRY_ENABLED=0
            - TICK_RATE_HZ=10
            - TRAINING_MODE_ENABLED=0
            - WORLD_SEED=1234
        networks:
            - coderone-tournament
    agent-a:
        extends:
            file: base-compose.yml
            service: python3-agent-dev
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentA&name=bruvbot
            - FWD_MODEL_CONNECTION_STRING=ws://fwd-server-a:6969/?role=admin
        depends_on:
            - game-server
        networks:
            - coderone-tournament

    agent-b:
     extends:
         file: base-compose.yml
         service: python3-hill_climber
     environment:
         - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentB&name=other
         - FWD_MODEL_CONNECTION_STRING=ws://fwd-server-b:6969/?role=admin
     depends_on:
         - game-server
     networks:
         - coderone-tournament


networks:
    coderone-tournament:
